version: "3.9"
services:
  nginx:
    image: nginx:1.21.0-alpine
    restart: always
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./config/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
  php:
    build: ./config/docker/php
    restart: always
    volumes:
      - .:/var/www/html